#! /bin/sh

DATEFTM="${DATEFTM:-+%a. %d. %b. %Y}"
SHORTFMT="${SHORTFMT:-+%d.%m.%Y}"
LABEL="${LABEL:-📅}"
blockdate=$(date "$DATEFTM")
shortblockdate=$(date "$SHORTFMT")

year=$(date '+%Y')
month=$(date '+%m')
case "$BLOCK_BUTTON" in
    1|2)
        date=$(date '+%A, %d. %B');;
    3)
        (( month == 12 )) && month=1 && year=$((year + 1)) || month=$((month + 1))
        date=$(cal $month $year | sed -n '1s/^  *//;1s/  *$//p')
esac
case "$BLOCK_BUTTON" in
    1|2|3)
export TERM=xterm
cal --color=always $month $year \
    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
    | tail -n +2 \
    | rofi \
        -dmenu \
        -width 5 \
        -lines 7 \
        -location 3 \
        -markup-rows \
        -no-fullscreen \
        -font "Monospace 10" \
        -hide-scrollbar \
        -bw 1 \
        -p "$date" > /dev/null \
        -yoffset 20 \
        -opacity "70" \
        -config ~/.config/i3blocks/scripts/rofi-calendar-config
    esac
echo "$LABEL $blockdate"
echo "$LABEL $shortblockdate"
