#!/bin/sh

if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
    updates_arch=0
fi

if ! updates_aur=$(yay -Qum 2> /dev/null | wc -l); then
# if ! updates_aur=$(cower -u 2> /dev/null | wc -l); then
# if ! updates_aur=$(trizen -Su --aur --quiet | wc -l); then
# if ! updates_aur=$(pikaur -Qua 2> /dev/null | wc -l); then
# if ! updates_aur=$(rua upgrade --printonly 2> /dev/null | wc -l); then
    updates_aur=0
fi

updates=$(("$updates_arch" + "$updates_aur"))

if [ "$button" -eq 1 ]; then
  pamac-manager --updates &
fi

if [ "$updates" -gt 0 ]; then
    echo "<span color='#FFC449'> $updates update</span>"
else
    #echo "<span color='#91712A' size='large' rise='-2500'></span> <span color='#888888'>no updates</span>"
    echo "<span color='#91712A'>📦 no updates</span>"
fi
